#!/bin/bash

# This script will run the command 'waybar' if gammastep isn't already running.
# If waybar is already running, it will run 'killall waybar'

if pgrep yambar > /dev/null
then
		killall yambar
else
		yambar &
fi
